name: Sync Backend to Hugging Face Hub

on:
  push:
    branches: [main]
    # This filter ensures the action ONLY runs when you change backend files
    paths:
      - "backend/**"

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # SOURCE: The folder in your GitHub repo to copy (backend)
        # DESTINATION: The name of your Hugging Face Space
        run: |
          git config --global user.email "harsh66287@gmail.com"
          git config --global user.name "harshh06"
          # 1. Create a temporary 'split' of just the backend folder
          # This calculates the git history for ONLY the backend folder
          SPLIT_HASH=$(git subtree split --prefix backend)

          # 2. Force push that specific history to Hugging Face
          # --force is the key here! It overwrites the history mismatch.
          git push --force https://harshsonii:$HF_TOKEN@huggingface.co/spaces/harshsonii/histopathology-scoring $SPLIT_HASH:main
